#ifndef QTINCLUDES_H
#define QTINCLUDES_H

#include <QGroupBox>
#include <QVBoxLayout>
#include <QCheckBox>
#include <QLabel>
#include <QLineEdit>
#include <QDialogButtonBox>
#include <QPushButton>
#include <QMessageBox>
#include <QSpinBox>
#include <QAction>
#include <QMenuBar>
#include <QFileDialog>
#include <QProgressDialog>
#include <QComboBox>
#include <QStylePainter>
#include <QStatusBar>
#include <QRadioButton>
#include <QButtonGroup>
#include <QVector>
#include <QtCore>
#include <QFile>
#include <QDir>
#include <QStandardPaths>
#include <QtGui>
#include <QString>
#include <QActionGroup>
#include <QElapsedTimer>
#include <QLayout>
#include <QStandardItemModel>
#include <QStatusBar>
#include <QAudioOutput>
#include <QAudioFormat>
#include <QAudioDeviceInfo>
#include <QTcpSocket>
#include <QTcpServer>
#include <QHostAddress>
#include <QAbstractSocket>
#include <QDataStream>
#include <QObject>
#include <QDebug>
#include <QtNetwork>
#include <QtSerialPort/QtSerialPort>
#include <QSerialPortInfo>
#include <QMessageBox>
#include <QDateTime>
#include <QTime>
#include <QtConcurrent/QtConcurrent>
#include <qmath.h>
#include "math.h"

#endif // QTINCLUDES_H
